# 行列演算の基礎

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [5]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [8]:
# 行列の定義
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [10]:
# 転置の計算
Xt = X.T
Xt

array([[1, 3],
       [2, 4]])

In [13]:
# 逆行列
# linear algebla: 線形代数
X_inv = np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
# 行列積
XX_inv = np.dot(X, X_inv)
XX_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

# よくある間違い

In [19]:
x = np.array([1,2,3])

In [20]:
x.T

array([1, 2, 3])

In [21]:
x2 = np.array([[1],[2],[3]])

In [22]:
x2.T

array([[1, 2, 3]])

# Numpyでよく使う処理

In [26]:
X = np.array([
    [2,3,4],
    [1,2,3]
])
X

array([[2, 3, 4],
       [1, 2, 3]])

In [27]:
X.shape

(2, 3)

In [30]:
row, col = X.shape

In [31]:
row

2

In [32]:
col

3

In [34]:
X.shape

(2, 3)

In [36]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


# 練習問題

In [40]:
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [43]:
y=np.array([[1],[5],[6],[8]])
y

array([[1],
       [5],
       [6],
       [8]])

In [46]:
# Step1
XtX = np.dot(X.T, X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [48]:
# Step2
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [50]:
#Step3
Xty = np.dot(X.T, y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [51]:
#Step4
W = np.dot(XtX_inv, Xty)
W

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# Scikit-learnで実装

In [52]:
import sklearn

In [53]:
from sklearn.linear_model import LinearRegression

In [69]:
# モデルの宣言
# model = LinearRegression()
model = LinearRegression(fit_intercept=False)

In [70]:
# モデルの学習
# パラメータの調整
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [71]:
# 調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [72]:
model.intercept_

0.0

In [76]:
# 予測精度 ← 決定係数
model.score(X, y)

0.6923076923076924

In [77]:
# 予測値の計算
x = np.array([[1,2,3]])

In [79]:
y_pred = model.predict(x)
y_pred

array([[3.]])